services:
  - type: web
    name: ruby-pendulum-api
    runtime: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: rails server -b 0.0.0.0 -p 3000
    plan: free
    healthCheckPath: /
    autoDeploy: true